### ISSUE TITLE
Open Pull Requests

### ISSUE THREAD

**Issue by toaster** [rwcarlsen/goexif#64]
Hi there,

I would like to contribute to the project but I am not sure if the PR would even be read. There are a lot of PRs open (some more than three years old).
Is the project still maintained or should I go for the goexif2 forks (despite the fact that the original one of these is looking for a new maintainer)?
If this project is still maintained: Why are the PRs not being merged or closed?

Best Regards

**Comment by rwcarlsen** [comment]
I've gotten busy with kids and a new job over the last few years and this just hasn't been making the priority list.  I've attempted to get a few other people involved in helping maintain it, but have not succeeded (obviously).  I can't foresee much changing on my availability in the near term.  Although I do occasionally peruse and merge smaller changes.  I'd be okay making you a collaborator if your interested.

**Comment by toaster** [comment]
Hi Robert, I can fully understand that.

For now I decided to use the exiv2 wrapper goexiv. But because I'm still in the phase of evaluation it might happen that I decide to use goexif instead. If so, I will reach out to you for collaborator access. For now it's not neccessary.

I wish you and your family all the best.
